### ISSUE TITLE
Atualizar README

### ISSUE THREAD

**Issue by evilfeeh** [danielgsantos15/curriculo#1]
@danielgsantos15 um projeto perfeito vai além da entrega do mesmo

Ter um readme coeso faz todo sentido para auxiliar seus colegas de trabalho e facilitar o code review e testes de funcionalidades

Você pode explicar um pouco mais do que foi feito no projeto, como alguém pode ter acesso, as tecnologias usadas e como rodar o seu projeto localmente.

**Comment by danielgsantos15** [comment]
Obrigado pelo feedback, vou atualizar!
